.Dd August 16, 2023
.Dt IMGCROP 1
.Sh NAME
.Nm imgcrop
.Nd simple image crop utility
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl i Ar input
.Op Fl o Ar output
.Op Ar geometry
.Sh DESCRIPTION
The
.Nm
utility lets you crop a region from an image.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl i
specify the input file path
.It Fl o
specify the output file path
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/imgcrop/issues
