.Dd November 2, 2022
.Dt PNGCROP 1
.Sh NAME
.Nm pngcrop
.Nd simple png crop utility
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Ar geometry
.Op Ar inpath
.Op Ar outpath
.Sh DESCRIPTION
The
.Nm
utility lets you crop a region from a png image.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/pngcrop/issues
